### ISSUE TITLE
Automobile Chart

### ISSUE THREAD

**Issue by Brandonhenk** [anthonykulis/automobile#1]
Hey, guys Im thinking it would be good if come Monday we can start coding. That means we need to try to get this UML completed by Monday. Here is the link to it https://www.lucidchart.com/invitations/accept/265211af-ac36-4560-aad4-8065b7f8c99d I restarted it and this one should be more correct. If you guys see anything that needs to be changed or added please tell me or if you can edit it thats fine if you want. Im confused on what would come from Luxury, Eco, and Sport from Cabin. I know it would be radio/nav and seats but if we placed that in each wouldn't we be going against the DRY rule. @Catyell2 @Richard-Davis91

**Comment by anthonykulis** [comment]
Is this resolved? Why hasn't your team chimed in? If this is done and was just a thought, close the issue. If it is on going, ping your team for a response. This shouldn't stand for 2 days with no replies.

**Comment by Catyell2** [comment]
Comment toward our team's pull request as of 3/7
@Brandonhenk I thought we were making progress in class today, what we need to do is just make it as bland as possible. We need to get a general idea down of what is going on.  Forgetting the code we just have to look at what matters to the body.  `body` has things associated with it like `truck` or `luxury` all at the same level (recall the whole universe thing talked about in class).  
Maybe what we should do is forget the DRY rule at first to just get everything down.  Once it is all down and makes some sort of sense then we can start polymorphing and implementing the DRY rule.

**Comment by Brandonhenk** [comment]
@Catyell2 I agree I worked on it earlier today and thought I figured it out and was totally wrong. He left me some feedback and I'm currently trying to work on it. But tomorrow we can go over it.

**Comment by Catyell2** [comment]
Ok cool.

**Comment by Brandonhenk** [comment]
![body 2 - page 1](https://cloud.githubusercontent.com/assets/25177376/23690866/68c2e438-038a-11e7-80d9-55a72462ad42.jpeg)

**Comment by Brandonhenk** [comment]
Didn't mean to do that, but the UML is not done but here is what I got

**Comment by anthonykulis** [comment]
@Catyell2 - 

> Comment toward our team's pull request as of 3/7
@Brandonhenk I thought we were making progress in class today, what we need to do is just make it as bland as possible. We need to get a general idea down of what is going on. Forgetting the code we just have to look at what matters to the body. body has things associated with it like truck or luxury all at the same level (recall the whole universe thing talked about in class).
Maybe what we should do is forget the DRY rule at first to just get everything down. Once it is all down and makes some sort of sense then we can start polymorphing and implementing the DRY rule.

Bland as possible is the exact opposite of what I want. I want it to be as expressive as possible. Also, DRY only applies to code. This is design. As soon as you all get these models into an expressive, ubiquitous language that others can easily understand (our team), then you figure out how to represent them with classes that are DRY and SUP/SRP.

**Comment by Brandonhenk** [comment]
Here are both links @Catyell2 @Richard-Davis91
https://www.lucidchart.com/invitations/accept/56edddaa-a8f2-427a-b913-b5c2ddd08271

https://www.lucidchart.com/invitations/accept/225fdba7-abd8-40ac-9883-0aafd1d6a199

**Comment by Brandonhenk** [comment]
I went through and tried to fix what he said we needed to fix. If you guys can please go through this and see if it makes sense and if anything needs to be changed. @Catyell2  @Richard-Davis91
![bodycomponents - page 1-4](https://cloud.githubusercontent.com/assets/25177376/24082132/974f5b26-0c8e-11e7-97cb-bfb30f46da6e.jpeg)
![bodycomponents - page 1-5](https://cloud.githubusercontent.com/assets/25177376/24082133/98b1fcda-0c8e-11e7-96c3-84e58d57ff79.jpeg)
![body 2 - page 1-6](https://cloud.githubusercontent.com/assets/25177376/24082134/9a71d54a-0c8e-11e7-9f2d-1535de3a5d08.jpeg)

**Comment by Catyell2** [comment]
The quarter panels, Paint, and Graphic all belong to 'parts' area that was
determined before, right?


On Mar 19, 2017 10:30 AM, "Brandonhenk" <notifications@github.com> wrote:

I went through and tried to fix what he said we needed to fix. If you guys
can please go through this and see if it makes sense and if anything needs
to be changed. @Catyell2 <https://github.com/Catyell2> @Richard_Davis91
[image: bodycomponents - page 1-4]
<https://cloud.githubusercontent.com/assets/25177376/24082132/974f5b26-0c8e-11e7-97cb-bfb30f46da6e.jpeg>
[image: bodycomponents - page 1-5]
<https://cloud.githubusercontent.com/assets/25177376/24082133/98b1fcda-0c8e-11e7-96c3-84e58d57ff79.jpeg>
[image: body 2 - page 1-6]
<https://cloud.githubusercontent.com/assets/25177376/24082134/9a71d54a-0c8e-11e7-9f2d-1535de3a5d08.jpeg>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/anthonykulis/automobile/issues/1#issuecomment-287624345>,
or mute the thread

**Comment by Brandonhenk** [comment]
@Catyell2 Im not sure what you mean. If you want to see what we had after class friday then check out the pull requests on anthonys automobile.

**Comment by Catyell2** [comment]
Alrighty will do.

On Mar 19, 2017 12:33 PM, "Brandonhenk" <notifications@github.com> wrote:

@Catyell2 <https://github.com/Catyell2> Im not sure what you mean. If you
want to see what we had after class friday then check out the pull requests
on anthonys automobile.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/anthonykulis/automobile/issues/1#issuecomment-287632730>,
or mute the thread
